### ISSUE TITLE
Famicom 3D System emulation

### ISSUE THREAD

**Issue by eadmaster** [rdanbrook/nestopia#155]
I know [not many games are compatible with this system](https://en.wikipedia.org/wiki/Famicom_3D_System), but it still would be interesting to have some suppport in Nestopia for this 3D glasses kit.

Also, for the libretro port i suggest a side-by-side filter for compatibility with the Google Cardboard and other VR headesets.
For mednafen-vb [a shader was made for this purpose](http://libretro.com/forums/showthread.php?t=2628) (i still have to try it).

**Comment by rdanbrook** [comment]
I want to say I'll support it, but I'm not sure of the scope of doing this.

**Comment by anikom15** [comment]
There are two 3D systems used, one for Family Computer and another NES. The Famicom used an active shutter 3D system, while the NES used passive anaglyph 3D.

The passive is simpler. Pressing SELECT for a compatible game enables anaglyph output. You can use any set of red-cyan glasses to view the image. To extract the two separate images from a single signal, you can use a long pass filter for the left-eye channel and a short pass filter for the right-eye channel. It may be possible to extract the images directly from the NES, however for a genuine experience, filters that emulate the 3D glasses should be used. The primary problem with this method is the extreme loss of color fidelity.

The active shutter system requires 3D glasses to be synced with the console. These glasses connect to an adapter with a TRS cable, and the adapter connects to the Famicom. The Famicom outputs the left-eye and right-eye channels every other frame, so one frame goes to the left eye, and the next goes to the right eye, &c. The Famicom is synced with the glasses so that the right eye is shuttered when the left channel is sent, and the left eye is shuttered when the right channel is sent. To get this to work with hardware, a driver needs to be written that sends an analog signal to an audio output going to the glasses. To extract the two channels, one simply needs to know which frames, odd or even, correspond with which eye. The primary problem with this system is reduced framerate and flickering due to the shuttering.

All games have a 2D mode, so there is no need to blend the 3D output.

**Comment by BenMcLean** [comment]
It should be possible to play these old games on a virtual screen using a VR headset if the emulator can run on them and is coded properly.

**Comment by rdanbrook** [comment]
@BenMcLean you have necroed a closed, 3 year old issue and added zero value to the conversation. This is an example of bad etiquette. Don't take this as an insult or attempt at castigation; take it as a "Bro, wtf?"

To further address the issue, doing this correctly would require a Vulkan renderer with multi-viewport capability. That is a possibility in the near future, but this project's goals have significantly changed in 3 years.
