### ISSUE TITLE
don't forget keypad binding

### ISSUE THREAD

**Issue by xuefer** [rdanbrook/nestopia#166]
nestopia is the best one for me, it has great compatibility and rewind. but when i forget to plug in USB keypad it forget keypad binding completely which is pretty annoying, can you please change this behavior?

**Comment by rdanbrook** [comment]
Can you give me details about your system?

**Comment by xuefer** [comment]
Windows 8.1, Chinese Simplified
Dragonrise Vibrate KeyPad

simply unplug USB keypad and start nestopia, all keypad binding is unset(clear). IIRC, it won't happen when nestopia is still running when i unplug keypad. it only happens when nestopia starts

**Comment by rdanbrook** [comment]
Since this is the old win32 release, it is out of scope for this project. The old codebase is too ugly to maintain. In the long run the cross-platform release will replace it completely. For now, I recommend either using the libretro port on Windows, or you could always update the win32 port if you want. I am accepting pull requests on https://github.com/rdanbrook/nestopia-win32
