### ISSUE TITLE
Alt f4 destroys config

### ISSUE THREAD

**Issue by jjfmz42015** [rdanbrook/nestopia#175]
Using alt f4 to terminate app seems to ruin config files, this method of exiting is useful with front ends. Can this be fixed?

**Comment by rdanbrook** [comment]
I can't reproduce it. What window manager are you using?

**Comment by jjfmz42015** [comment]
Im using Nestopia UE 1.47 on WIndows 7 x64 on 2 different machine, I was using romshelf2 as a front end but no stopped to do some testing.

On both of my computers with multiple random roms tested using alt+f4 to exit works, however the odd time it seems to corrupt the config or something which forces me to delete and put a fresh folder containing nestopia.

this is random but if you load nestopia, load a rom and alt+f4 to exit do this multiple times usually by anywhere between 10 and 20 time corruption will occur.

Not a huge issue but I assume something that could be fixed?

The way nestopia works is something loaded in ram that can be lost during alt+f4 that will result in the corruption?

note on the same systems this does not happen with any other emulator.

If you would like me to test something let me know.

**Comment by rdanbrook** [comment]
So is it the old win32 interface or the alpha-quality release I put out a few months back?

**Comment by jjfmz42015** [comment]
the old win32

**Comment by rdanbrook** [comment]
In that case, this issue should actually be filed in the other repo that is specific to the win32 port: https://github.com/rdanbrook/nestopia-win32

I'm no longer doing active development on that (unless the answer is simple), because the code has rotted, and uses old technologies, and I don't want to spend time working on it when I would rather beef up the cross-platform port to the point that it can fully replace the win32 port. I will accept pull requests though.

**Comment by jjfmz42015** [comment]
I can't get the alpha to run and I tried it on 4 Windows machines three have win 7 64 bit and one has win 10
