### ISSUE TITLE
(multiplatform) add 4:3 aspect ratio

### ISSUE THREAD

**Issue by eugene-s-nesdev** [rdanbrook/nestopia#193]
Request: can you add 4:3 aspect ratio to multiplatform-port and maybe to old windows legacy port too?
Current version seems have only NTSC 8:7 (PAR)

This PAL TV-test must look like: 
http://savepic.su/7403052.png

http://nesdev.com/Gits2.zip

**Comment by rdanbrook** [comment]
Shouldn't be a problem, will do next time I have time.

**Comment by rdanbrook** [comment]
I can make this test pass by changing the internal width to 320. I'm not sure that's accurate, because: http://wiki.nesdev.com/w/index.php/Overscan#PAL

384x288 is 4:3, just as 320x240. However, the tvpassfail test claims the ratio is 48:35, and I must make the width much wider to pass that test for PAL.

As I am not from Europe I don't have any insight into what is correct here. If the tvpassfail test is unreliable, then I have code ready that will allow us to close this issue and enable a 4:3 mode.

**Comment by eugene-s-nesdev** [comment]
Sorry, I can't tell you exact about accuracy. 
But standard 4:3 aspect (you mentioned) is present in many emulators (punes, fceux, bizhawk etc), and PAL-users love it, including me. I think it's enough.
Thank you for fixing region-selector!

**Comment by rdanbrook** [comment]
I just made the TV Aspect Ratio option change the size depending on the region. Dendy will be stretched to PAL widths as well.
