### ISSUE TITLE
Autotooling/CMake the build system

### ISSUE THREAD

**Issue by SoapGentoo** [rdanbrook/nestopia#211]
Dear authors,
would you consider eithre Autotooling or CMake'ing the build system? If you are open for either, I would be willing to send in a PR that to make it happen.

Both Autotools and CMake are much easier to use for consumers, allow for better VPATH support, provide better Makefiles and make our downstream much easier. Please think of all the distributions that have tools in place to work with Autotools and CMake!

**Comment by rdanbrook** [comment]
I'm not a big fan of either build system (or any build system beyond static makefiles), which is why it was not done previously. However, I am open minded about it if it can be done cleanly. To be honest I have never worked with either build system beyond using them to build other projects, so I'm not sure what changes I may need to make to the codebase.

**Comment by SoapGentoo** [comment]
@rdanbrook the problem with static Makefiles is that for distributions, they follow no conventions. For instance, the current Makefile does not allow for staged installations, which is important, as we never install into the destination directly. Furthermore, they are more amenable to changing paths and providing options. If you are open, I could put together a simple CMake based build system. It is unlikely that you will have to change anything in the code base, and even if so, it would be minimal.

**Comment by rdanbrook** [comment]
@SoapGentoo if you build it I will merge it. I would like to keep the static makefile around for the time being for a smooth transition though. It may also be time for me to learn cmake in depth, since many projects I follow are using it.
